### ISSUE TITLE
Double quotes in game (shortcut) names need to be escaped with backslashes in screenshots.vdf

### ISSUE THREAD

**Issue by joyrider3774** [doZennn/steam-rom-manager#296]
I had an issue on my steamdeck where my steam would not boot anymore after using steam rom manager. I have investigated this issue and found the culprit to be double quotes (`"`) in game names inside screenshots.vdf which steam rom manager added. 

There are games that have double quotes inside their names, if you create such non steamshortcut yourself and you take a screenshot in such game steam seem's to add a backslash to the double quote basically escaping the character.

![image](https://user-images.githubusercontent.com/10714776/167212526-0f24d561-8103-4052-8cc1-fdfc28a72909.png)

Steam rom manager does not seem todo this 

For example use the following filename as a rom `Insector X (USA).zip` let it be searched using fuzzy matching. It will mismatch (notice the double quotes only last character is real double quote)

![image](https://user-images.githubusercontent.com/10714776/167213007-e3376224-b706-44e1-91e0-6a27d541a829.png)

Steam rom manager saves this inside screenshots.vdf without an escped doubled quote

![image](https://user-images.githubusercontent.com/10714776/167213198-9222be5c-55f0-4d0c-8a69-da2937e17d9c.png)

resulting in errors when starting steam and potentially (as i had encountered) steam crashing
![image](https://user-images.githubusercontent.com/10714776/167213378-ade63d4f-ab86-46dc-bc88-ecd7549c0abc.png)
it does not always crash steam but does make steam error out on parsing screenshot.vdf

When i manually removed double quotes in my screenshots.vdf steam booted again without problems

**Comment by joyrider3774** [comment]
might want to check what it does when a game name contains a backslash and it's possible as someone else said on discord that you need to escape anything that requires escaping in json

**Comment by doZennn** [comment]
Looks like screenshots.vdf uses the non-binary VDF spec. There are some notes about escaping in the Source docs here: https://developer.valvesoftware.com/wiki/KeyValues

All of the control characters `{, } and "` should be escaped, imo.

**Comment by cbartondock** [comment]
Fixed as of 2.3.33

**Comment by joyrider3774** [comment]
@cbartondock it's not completely fixed, there is a spot in the source code that was forgotten and we did not think about. SRM adds the titles correctly now 
![image](https://user-images.githubusercontent.com/10714776/167296564-6eab7729-a068-4e90-9bdb-1eb498c9350f.png)

but when adding the entries for images like logo's grids etc it does not do it and these are also in the same list and should also be escaped normally i think as they are added to the same list
![image](https://user-images.githubusercontent.com/10714776/167296567-4dd7bf7e-cdde-4519-973f-d7a8d7b3c8be.png)
