### ISSUE TITLE
Path undefined error on UPlay even on 2.3.40

### ISSUE THREAD

**Issue by DevSecTim** [doZennn/steam-rom-manager#355]
"TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined" when testing UPlay parser even with confirmed UPlay install in C:\Program Files (x86)\Ubisoft - this is the error reportedly fixed in 2.3.40 but I am still getting it on this parse specifically - any ideas?

Many thanks
Tim

**Comment by djibux** [comment]
I confirm the issue. Couldn't get the parser to work on a fresh install.

**Comment by ZeroOne010101** [comment]
Can confirm, v2.3.40, up-to-date uplay installation.

**Comment by cbartondock** [comment]
If any or all of you could comment the list of UPlay titles you have that would be very helpful.

**Comment by cbartondock** [comment]
I am 90% confident this is fixed in 2.3.51. Comment if I need to re-open.

**Comment by djibux** [comment]
Thanks for looking into that.
The issue is not solved for me.  I no longer have an error, but no games are detected.  Log is pretty much empty: it only displays the operating system (Windows 11).
I have quite a few games installed: Assassin’s Creed II, Assassin’s Creed Syndicate, Far Cry 3, Rayman Legends, Rayman Origins, Ghost Recon Breakpoint, The Division 1 & 2, Watch Dogs 2… 
Let’s see if others have the same problem before reopening the issue.

**Comment by cbartondock** [comment]
Weird. Some of those exact games work fine for me.

**Comment by cbartondock** [comment]
If you want to help debug it dm me on discord @lontanadascienza
