### ISSUE TITLE
Steam Deck Timeouts Issue

### ISSUE THREAD

**Issue by TheGor1lla** [doZennn/steam-rom-manager#543]
Using a Steamdeck, once I parsed all my titles (~270) I can see all the artwork downloaded (All Artwork selected).  

When I use "Save to Steam" I get errors for about 90% of my games after a few seconds:  

```
Error: Non fatal errors occurred while writing:  
Error for title <title>:  
TimeoutError: Timeout awaiting request for 10000ms
```  

Games add fine, but the artworks are missing. My WiFi connection seems fine

**Comment by cbartondock** [comment]
Yeah this is a known issue (only on decks and only on some devices). Thanks for adding it here. It *might* be fixed in the next release which is imminent.

**Comment by TheGor1lla** [comment]
Sorry, must have missed other reports.  

Is there any way one can help with testing?

**Comment by cbartondock** [comment]
New release is out, give it a go and let me know if it fixes it. Also yes I am going to start recruiting beta testers on the discord soon.

**Comment by Anmonpi** [comment]
Started happening to me as i updated to 2.4.15, never happened before. 
I'm also using a Steam Deck

**Comment by TheGor1lla** [comment]
Just got around to testing it. Sadly it still happens, sent the complete error log from within the application.

**Comment by cbartondock** [comment]
Yeah discord users are seeing the same thing. It's my highest priority right now SRM wise but unfortunately I don't have a deck so it's difficult for me to test. If you're willing to help debug DM me @lontanadascienza on the sgdb discord.

**Comment by TheGor1lla** [comment]
Sure can do, but probably not until tomorrow-ish

**Comment by TheLastNinja2023** [comment]
Same issue here since I updated
Is there a way to go back to a previous version of Steam rom Manager ?

**Comment by TheGor1lla** [comment]
> Same issue here since I updated Is there a way to go back to a previous version of Steam rom Manager ?

You can download older AppImages from https://github.com/SteamGridDB/steam-rom-manager/releases  

Which versions did you have before that were working? Was it on the Steamdeck?  

@Anmonpi

**Comment by DocMAX** [comment]
Same here on a GPD WIN 4 (normal windows installation) - plenty of errors...

![grafik](https://user-images.githubusercontent.com/5351323/236705275-42205e85-ce0a-47a6-8654-7a8edda908c6.png)

**Comment by Macster70** [comment]
Same errors here on AMD Ryzen mini PC (Beelink 5800H) using SteamDeck OS via Holo ISO.

**Comment by frukbachers** [comment]
I remembered that steam deck or their version of linux has sometimes issues with wireless reception, to the point where some random guy said to disable wifi, restart, enable wifi and again restart helped fix the issue.

You can try that or instead, what I did to resolve this issue 5 minutes ago, is dock my deck and have it connect via LAN. That resolved it, at least on my end.

Please let me know if this helps any of you.

**Comment by cbartondock** [comment]
@Macster70 dm me on discord @lontanadascienza if you want to help debug this, I have some builds that might fix it.

**Comment by Macster70** [comment]
> @Macster70 dm me on discord @lontanadascienza if you want to help debug this, I have some builds that might fix it.
That worked - connecting a LAN cable and it updated correctly. Many thanks.


> I remembered that steam deck or their version of linux has sometimes issues with wireless reception, to the point where some random guy said to disable wifi, restart, enable wifi and again restart helped fix the issue.
> 
> You can try that or instead, what I did to resolve this issue 5 minutes ago, is dock my deck and have it connect via LAN. That resolved it, at least on my end.
> 
> Please let me know if this helps any of you.

**Comment by Macster70** [comment]
Thanks frukbachers and cbartondock - connecting the LAN cable resolved the issue. Many thanks for your assistance.

**Comment by YunJerrod** [comment]
@frukbachers thank you, ethernet cable instead of WiFi did the job ;-)

**Comment by TheGor1lla** [comment]
We were testing with a reduced batch size, which worked for the Steam Deck. Should be included in a new release soon

**Comment by cbartondock** [comment]
Incoming, yes.

**Comment by cbartondock** [comment]
Fixed in 2.4.16

**Comment by Portal-Engineering** [comment]
I am still having this problem on my Steam Deck. I am on 2.4.16 
same timeout error

**Comment by DarkArcanine** [comment]
I think I ran into the solution. SRM has hardcoded DNS servers (1.1.1.1 and 8.8.8.8) if these are blocked by firewall it will timeout. I couldn't get it to work within my home network (blocks every non-local-pihole DNS request) for hours. Then I tried using my phone's hotspot and it worked flawlessly. I tracked this problem using my firewall logs and there it was... I fixed it in two ways, allow external DNS requests or do a NAT forward to local pihole.

**Comment by Portal-Engineering** [comment]
I tried it from a hotspot and ran into the same timeout issue. 

Tried it from a lan cable and tried it from wifi and got the same timeout.

**Comment by TheGor1lla** [comment]
@Portal-Engineering Have you tried to lower the batch size? Or try what DarkArcanine said?

**Comment by Portal-Engineering** [comment]
Yes I tried what DarkA said to try. Posters and icons worked but I still get a timeout for banners/heroes. Weird

**Comment by Portal-Engineering** [comment]
I will try to reduce the batch size next.

**Comment by Portal-Engineering** [comment]
I reduced my library to 60 and I am still experiencing the issue. Posters and icons are saved but no banners/heroes

**Comment by macky733** [comment]
I literally just made an account to say that i’m having this exact same issue as of 2.4.17.

I had to roll back to 2.4.16 and it’s working there, so i know that it’s nothing wrong with my deck.

**Comment by Portal-Engineering** [comment]
I no longer have any problems with 2.4.17

All my roms and emulators have proper artwork now. Thanks guys 🙂

**Comment by Karrq** [comment]
Came here because I have this issue as well.
SD 64GB - brand new.
Artwork shows in the app but I see in the logs timeouts for everything (have about 10 things), and then on steam it's empty

The error on the timeouts is `connect EHOSTUNREACH <ipv6 addr>`

**Comment by Karrq** [comment]
Found a fix for my issue!
Had to specify IPv6 `disabled` (instead of ignored) in my WiFi configuration as it wasn't supported by my internet provider.
After that, no more timeout issue :)
