### ISSUE TITLE
[BUG] Parsing breaks steam screenshot manager

### ISSUE THREAD

**Issue by tobiasriper** [doZennn/steam-rom-manager#758]
Parsing and saving games to steam with SRM breaks the screenshot manager as of Aug 2025 so previews no longer work in the screenshot and recording window and new screenshots don't show up in this window either (even non SRM, steam games). You have to delete the screenshots.vdf file to let the screenshot manager rebuild.

**Comment by kevinfiol** [comment]
Seems to still happen on SRM version 2.5.30. I'm running Linux Kernel 6.16 on Fedora 42.

**Comment by vaner-org** [comment]
This has been a problem for over a year. SRM is unable to manage game IDs between parses and adds duplicate entries to screenshots.vdf.

**Comment by DEDantiSocial** [comment]
Is there any way to fix this issue?

**Comment by vaner-org** [comment]
If this is affecting you, you have to navigate to to Steam > userdata > [your user] > 760 > screenshots.vdf. ~~Open this in a text editor, go to the end of the file, under "shortcutnames", look for duplicate entries, delete those, and search the list above for any references to those entries, and delete those blocks too.~~

Alternatively, you can just delete screenshots.vdf and have steam manually rebuild it, though that breaks other things like Steam knowing which screenshots have already been uploaded, and so should be linked with their cloud variant. But running SRM is equivalent to corrupting screenshots.vdf anyway, so you may as well.

**Comment by DEDantiSocial** [comment]
> If this is affecting you, you have to navigate to to Steam > userdata > [your user] > 760 > screenshots.vdf. Open this in a text editor, go to the end of the file, under "shortcutnames", look for duplicate entries, delete those, and search the list above for any references to those entries, and delete those blocks too.
> 
> Alternatively, you can just delete screenshots.vdf and have steam manually rebuild it, though that breaks other things like Steam knowing which screenshots have already been uploaded, and so should be linked with their cloud variant. But running SRM is equivalent to corrupting screenshots.vdf anyway, so you may as well.

Hello. Thank you for the reply. I was able to fix it by deleting the file mentioned in the other post.

**Comment by tobiasriper** [comment]
I wish we could just get a real solution. Parsing is now a pain be cause then I have to delete the .vdf file and wait for the long rebuild process and then steam doesn't know whats uploaded. And the other solution seems really tedious. I don't get why no one is paying attention to this from the dev side because its really annoying.

**Comment by espiox** [comment]
Would it be possible to create some kind of script to automatically remove duplicates from screenshots.vdf without having to do the full rebuild?

**Comment by Aepoh** [comment]
It is embarrassing that this is still happening.

**Comment by vaner-org** [comment]
> Would it be possible to create some kind of script to automatically remove duplicates from screenshots.vdf without having to do the full rebuild?

That effort could be better directed at fixing this entirely, it is open source after all. And, taking a look now, the problem seems to have worsened since I last checked. It isn't just duplicate entries anymore, the entire file seems scrambled.

In the meantime, you could make a backup of screenshots.vdf before doing a parse, and then replace the new file with the backup.

To simplify this process, make a git repository out of your 760 folder, and after running SRM, just discard changes made to screenshots.vdf and screenshots.backup, and restart Steam. This seems to work for me, I've managed to successfully add a new game and keep older games' screenshots intact, no rebuild needed.

I'm not sure what the purpose of SRM messing with the screenshots database is to begin with, since steam seems to self-manage screenshots against game IDs just fine.

**Comment by vaner-org** [comment]
Also, I've figured out a way to relink uploaded screenshots with their local equivalents so there aren't duplicates after the rebuild.

First, get the screenshot's file ID via it's uploaded link: `https://steamcommunity.com/sharedfiles/filedetails/?id=XXXXXXXXXX `
Then, find the local screenshot's entry in screenshots.vdf, and at the end, replace the following fields, and add "publishedfileid" with the X's replaced with the correct ID for each file.
```
"Permissions"		"8"
"hscreenshot"		"11751511215788145870"
"publishedfileid"		"XXXXXXXXXX"
```

Once your library is fixed, I'd really recommend using git to undo any changes SRM makes to your file.

**Comment by tobiasriper** [comment]
Devs can you please look at this issue ? I don't get why more people aren't discussing this.

**Comment by espiox** [comment]
Agreed, I'm very hesitant to even use SRM until this issue is resolved, now that I finally repaired my Steam media gallery.

**Comment by unosofmanila** [comment]
**The Issue**:
When SRM parses and saves the screenshots.vdf file, it loses precision on large 64-bit unsigned integers, specifically in the gameid and hscreenshot fields. This effectively "breaks the link" between the Steam database and the actual screenshot folders on the disk.

**Details**:
Rounding Error: Values like 18446744073709551615 are being rounded to 18446744073709552000.

Floating Point Limitation: This suggests the parser is treating these values as 64-bit floats (doubles), which only have ~15-17 significant decimal digits of precision. Since these IDs require all 20 digits, the tail end of the number is lost.

Result: Steam fails to recognize the corrected IDs, leading to screenshots disappearing from the library entirely because the gameid in the VDF no longer matches the folder name on the drive (e.g., folder ...139392 vs VDF ID ...140000).

**Requested Fix:**
Ensure the VDF parser/writer treats the gameid and hscreenshot values strictly as Strings or BigInts (64-bit integers) to preserve bit-perfect accuracy during the read/write cycle.


Until it gets fixed. I have a PowerShell script anyone can run that fixes the vdf after SRM parses it. Although SRM corrupts the gameid, the ID in the folderpath is intact so it can just reference from there. The screenshot value is just a constant.

**Comment by cbartondock** [comment]
> **The Issue**: When SRM parses and saves the screenshots.vdf file, it loses precision on large 64-bit unsigned integers, specifically in the gameid and hscreenshot fields. This effectively "breaks the link" between the Steam database and the actual screenshot folders on the disk.
> 
> **Details**: Rounding Error: Values like 18446744073709551615 are being rounded to 18446744073709552000.
> 
> Floating Point Limitation: This suggests the parser is treating these values as 64-bit floats (doubles), which only have ~15-17 significant decimal digits of precision. Since these IDs require all 20 digits, the tail end of the number is lost.
> 
> Result: Steam fails to recognize the corrected IDs, leading to screenshots disappearing from the library entirely because the gameid in the VDF no longer matches the folder name on the drive (e.g., folder ...139392 vs VDF ID ...140000).
> 
> **Requested Fix:** Ensure the VDF parser/writer treats the gameid and hscreenshot values strictly as Strings or BigInts (64-bit integers) to preserve bit-perfect accuracy during the read/write cycle.
> 
> Until it gets fixed. I have a PowerShell script anyone can run that fixes the vdf after SRM parses it. Although SRM corrupts the gameid, the ID in the folderpath is intact so it can just reference from there. The screenshot value is just a constant.

This appears to actually be a problem in [@node-steam/vdf](https://github.com/node-steam/vdf). I have submitted a [PR](https://github.com/node-steam/vdf/pull/22) that I believe will fix it. Thanks everyone for your detective work, especially @unosofmanila. 

I've switched over to my fork of @node-steam/vdf on SRM master. If anyone has bandwidth to test this (I don't), I'll close this issue and push a new release of SRM.

Also @tobiasriper, as a general principle open source development is slow to fix specific problems unless 
a) there are a lot of active developers (SRM has one barely active dev, me)
b) you fix it yourself. 

Creating issues is helpful, adding details about possible causes or fixes is helpful. Repeatedly questioning why "the devs" haven't fixed something yet is not helpful, it's entitlement to other people's time that they do not owe you.

**Comment by 0x3e** [comment]
I do not have tests for https://github.com/cbartondock/vdf but have done testing. The changes from prior to your changes I have found are summarised in gist diffs below. A remaining issue I have identified is with the javascript numbers for Infinity you may want to consider:

```
      if (+v === Number.POSITIVE_INFINITY) v = String(v)
      else if (+v === Number.NEGATIVE_INFINITY) v = String(v)
      else if (v !== "" && !Number.isNaN(v) && String(+v) === v) v = +v
```

Your changes look good to me and I eagerly await a release of steam-rom-manager I can use with my main username.

Diffs 
https://gist.github.com/0x3e/9792486d380dbe792436d0b6d2a13b83
Output json from my test vdf files for your changes, the roundtrips vdf -> json -> vdf are now without issue ( but more strings in the resultant json):
https://github.com/0x3e/vdf/tree/node-steam/vdf/issues/10/fixtures/cbartondock_vdf
My update on an which could be the core of the problem:
https://github.com/node-steam/vdf/issues/10#issuecomment-4737483621

**Comment by cbartondock** [comment]
> I do not have tests for https://github.com/cbartondock/vdf but have done testing. The changes from prior to your changes I have found are summarised in gist diffs below. A remaining issue I have identified is with the javascript numbers for Infinity you may want to consider:
> 
> ```
>       if (+v === Number.POSITIVE_INFINITY) v = String(v)
>       else if (+v === Number.NEGATIVE_INFINITY) v = String(v)
>       else if (v !== "" && !Number.isNaN(v) && String(+v) === v) v = +v
> ```
> 
> Your changes look good to me and I eagerly await a release of steam-rom-manager I can use with my main username.
> 
> Diffs https://gist.github.com/0x3e/9792486d380dbe792436d0b6d2a13b83 Output json from my test vdf files for your changes, the roundtrips vdf -> json -> vdf are now without issue ( but more strings in the resultant json): https://github.com/0x3e/vdf/tree/node-steam/vdf/issues/10/fixtures/cbartondock_vdf My update on an which could be the core of the problem: [node-steam/vdf#10 (comment)](https://github.com/node-steam/vdf/issues/10#issuecomment-4737483621)

Thank you for your testing! I'll push the release of SRM that fixes this and close out the issue. I don't think infinite numbers will be a problem for SRM, but you could submit an issue to node-steam/vdf

**Comment by cbartondock** [comment]
Okay pushing a release for this now and closing it! Let me know if it needs to be re-opened.

**Comment by tobiasriper** [comment]
> > **The Issue**: When SRM parses and saves the screenshots.vdf file, it loses precision on large 64-bit unsigned integers, specifically in the gameid and hscreenshot fields. This effectively "breaks the link" between the Steam database and the actual screenshot folders on the disk.
> > **Details**: Rounding Error: Values like 18446744073709551615 are being rounded to 18446744073709552000.
> > Floating Point Limitation: This suggests the parser is treating these values as 64-bit floats (doubles), which only have ~15-17 significant decimal digits of precision. Since these IDs require all 20 digits, the tail end of the number is lost.
> > Result: Steam fails to recognize the corrected IDs, leading to screenshots disappearing from the library entirely because the gameid in the VDF no longer matches the folder name on the drive (e.g., folder ...139392 vs VDF ID ...140000).
> > **Requested Fix:** Ensure the VDF parser/writer treats the gameid and hscreenshot values strictly as Strings or BigInts (64-bit integers) to preserve bit-perfect accuracy during the read/write cycle.
> > Until it gets fixed. I have a PowerShell script anyone can run that fixes the vdf after SRM parses it. Although SRM corrupts the gameid, the ID in the folderpath is intact so it can just reference from there. The screenshot value is just a constant.
> 
> This appears to actually be a problem in [@node-steam/vdf](https://github.com/node-steam/vdf). I have submitted a [PR](https://github.com/node-steam/vdf/pull/22) that I believe will fix it. Thanks everyone for your detective work, especially [@unosofmanila](https://github.com/unosofmanila).
> 
> I've switched over to my fork of @node-steam/vdf on SRM master. If anyone has bandwidth to test this (I don't), I'll close this issue and push a new release of SRM.
> 
> Also [@tobiasriper](https://github.com/tobiasriper), as a general principle open source development is slow to fix specific problems unless a) there are a lot of active developers (SRM has one barely active dev, me) b) you fix it yourself.
> 
> Creating issues is helpful, adding details about possible causes or fixes is helpful. Repeatedly questioning why "the devs" haven't fixed something yet is not helpful, it's entitlement to other people's time that they do not owe you.


I appreciate you volunteering your time to SRM and I appreciate that you don't 'owe' me any of your time.

The frustration for me was really the lack of acknowledgement. If you don't want to fix a bug or don't have the time I have no issues with that. But if you at least acknowledge its a bug and say not sure if it will ever be fixed then thats fine and I can move on. But not even acknowledging the issue (which was not a minor issue by the way) is pretty frustrating as a user.

So I would say that if you care about what you have made and someone brings up a steam functionality breaking bug at least nodding and saying 'we know' or 'I haven't tested this to verify if its true or not'.   That way I know that at least the sole dev on the project heard what I had to say.

Once again I thank you for your effort. I recognize that you are not being paid for it but I did not force you to make or work on SRM I am simply a user reporting back on a non-minor steam breaking issue. I care about SRM. I think its a fantastic concept and when it does work its great and that is why I am volunteering MY TIME to discuss it, bring attention to a problem and hopefully have you and others improve it. I am sorry I could not fix it myself, if I could I would.

In the future I will not repeatedly say 'how come the devs haven't fixed this?' but if I find a huge problem and I am getting no responses for months I will say 'Are the devs/ users aware of this?' and I think saying that is not a sign of 'entitlement' but instead of care towards a piece of software I enjoy using and would like to see improve not just for me but for 1000s of users/gamers around the world.

**Comment by cbartondock** [comment]
I have confirmed that it is fixed (at least for me) so long as you delete your broken screenshots.vdf and go from there.

**Comment by vaner-org** [comment]
Do all pre-existing screenshots still show up as Steam notifications on startup after a parse?

**Comment by cbartondock** [comment]
yes

**Comment by unosofmanila** [comment]
Thank you for the fix. Glad my comment helped.

**Comment by lyndon025** [comment]
Just wanted to say thanks for this report. so this is what was probably causing my screenshots to break all the time, i actually have been having this issue for 2 years now seemingly randomly and i keep on just deleting screenshots.vdf when it happens. I did a google search and somehow the query led me to this issue and now i have connected the issue to SRM in which i indeed recently used to parse maybe a month ago! so yeah, thanks for this. I haven't really confirmed it yet because my screenshots are still building at the moment but I hope it doesnt happen again.
